from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Any

from .client import GarminClient

logger = logging.getLogger(__name__)

# Garmin workout constants
SPORT_TYPE_STRENGTH = {
    "sportTypeId": 5,
    "sportTypeKey": "strength_training",
}

STEP_TYPES = {
    "warmup": {"stepTypeId": 1, "stepTypeKey": "warmup"},
    "cooldown": {"stepTypeId": 2, "stepTypeKey": "cooldown"},
    "exercise": {"stepTypeId": 3, "stepTypeKey": "interval"},
    "recovery": {"stepTypeId": 4, "stepTypeKey": "recovery"},
    "rest": {"stepTypeId": 5, "stepTypeKey": "rest"},
}

END_CONDITIONS = {
    "lap_button": {"conditionTypeId": 1, "conditionTypeKey": "lap.button"},
    "time": {"conditionTypeId": 2, "conditionTypeKey": "time"},
    "iterations": {"conditionTypeId": 7, "conditionTypeKey": "iterations"},
    "reps": {"conditionTypeId": 10, "conditionTypeKey": "reps"},
}

WEIGHT_UNIT_KG = {"unitId": 8, "unitKey": "kilogram", "factor": 1000.0}
WEIGHT_UNIT_LB = {"unitId": 9, "unitKey": "pound", "factor": 453.592}


def build_workout_json(plan: dict[str, Any]) -> dict[str, Any]:
    """Convert an AI-generated plan to Garmin workout JSON.

    plan format:
    {
        "name": "Push Day",
        "exercises": [
            {"category": "BENCH_PRESS", "exercise": "SMITH_MACHINE_BENCH_PRESS",
             "sets": 4, "reps": 10, "weight_kg": 60, "rest_sec": 90},
            ...
        ]
    }
    """
    workout_steps = []
    step_order = 1

    for ex in plan["exercises"]:
        # Build a RepeatGroupDTO for the sets
        exercise_step = _build_exercise_step(ex, step_order)
        rest_step = _build_rest_step(ex.get("rest_sec", 90), step_order + 1)

        repeat_group = {
            "type": "RepeatGroupDTO",
            "stepOrder": step_order,
            "stepType": {"stepTypeId": 6, "stepTypeKey": "repeat"},
            "numberOfIterations": ex["sets"],
            "endCondition": END_CONDITIONS["iterations"],
            "endConditionValue": float(ex["sets"]),
            "smartRepeat": False,
            "workoutSteps": [exercise_step, rest_step],
        }

        workout_steps.append(repeat_group)
        step_order += 1

    return {
        "workoutName": plan.get("name", "AI Coach Workout"),
        "description": "Generated by Garmin AI Coach",
        "sportType": SPORT_TYPE_STRENGTH,
        "workoutSegments": [
            {
                "segmentOrder": 1,
                "sportType": SPORT_TYPE_STRENGTH,
                "workoutSteps": workout_steps,
            }
        ],
    }


def _build_exercise_step(ex: dict[str, Any], order: int) -> dict[str, Any]:
    step = {
        "type": "ExecutableStepDTO",
        "stepOrder": 1,
        "stepType": STEP_TYPES["exercise"],
        "endCondition": END_CONDITIONS["reps"],
        "endConditionValue": float(ex.get("reps", 10)),
        "category": ex.get("category", ""),
        "exerciseName": ex.get("exercise", ""),
        "targetType": {"workoutTargetTypeId": 1, "workoutTargetTypeKey": "no.target"},
    }

    weight = ex.get("weight_kg")
    if weight is not None and weight > 0:
        step["weightValue"] = float(weight)
        step["weightUnit"] = WEIGHT_UNIT_KG

    return step


def _build_rest_step(rest_sec: int, order: int) -> dict[str, Any]:
    return {
        "type": "ExecutableStepDTO",
        "stepOrder": 2,
        "stepType": STEP_TYPES["rest"],
        "endCondition": END_CONDITIONS["time"],
        "endConditionValue": float(rest_sec),
        "targetType": {"workoutTargetTypeId": 1, "workoutTargetTypeKey": "no.target"},
    }


def upload_workout(client: GarminClient, plan: dict[str, Any]) -> str | None:
    """Build Garmin workout JSON from AI plan and upload it.

    Returns the workout ID if successful, None otherwise.
    """
    workout_json = build_workout_json(plan)

    try:
        response = client.client.upload_workout(workout_json)
        workout_id = None
        if isinstance(response, dict):
            workout_id = response.get("workoutId")
        logger.info("Workout uploaded: %s (id: %s)", plan.get("name"), workout_id)
        return str(workout_id) if workout_id is not None else "uploaded"
    except Exception as e:
        logger.error("Failed to upload workout: %s", e)
        return None


def update_workout(client: GarminClient, workout_id: str, plan: dict[str, Any]) -> bool:
    """Update an existing Garmin workout with new plan data."""
    workout_json = build_workout_json(plan)
    workout_json["workoutId"] = int(workout_id)

    try:
        client.client.garth.connectapi(
            f"/workout-service/workout/{workout_id}",
            method="PUT",
            json=workout_json,
        )
        logger.info("Workout updated: %s (id: %s)", plan.get("name"), workout_id)
        return True
    except Exception as e:
        logger.error("Failed to update workout %s: %s", workout_id, e)
        return False


def load_workout_tracker(data_dir: Path) -> dict[str, Any]:
    path = data_dir / "memory" / "workouts.json"
    if path.exists():
        return json.loads(path.read_text())
    return {}


def save_workout_tracker(data_dir: Path, tracker: dict[str, Any]) -> None:
    path = data_dir / "memory" / "workouts.json"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(tracker, indent=2))


def format_plan_text(plan: dict[str, Any]) -> str:
    """Format an AI plan as human-readable text for Telegram."""
    lines = [f"📋 {plan.get('name', 'Workout')}"]
    lines.append("")

    for i, ex in enumerate(plan.get("exercises", []), 1):
        exercise_name = ex.get("exercise", "Unknown").replace("_", " ").title()
        sets = ex.get("sets", 3)
        reps = ex.get("reps", 10)
        weight = ex.get("weight_kg")
        rest = ex.get("rest_sec", 90)

        weight_str = f" @ {weight}kg" if weight is not None else ""
        rest_str = f"{rest // 60}min" if rest >= 60 else f"{rest}s"

        lines.append(f"{i}. {exercise_name}")
        lines.append(f"   {sets}x{reps}{weight_str} | Rest {rest_str}")
        lines.append("")

    return "\n".join(lines)
